/*
 * npu_platform_resource.h
 *
 * about npu platform resource
 *
 * Copyright (c) 2012-2019 Huawei Technologies Co., Ltd.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 */
#ifndef __NPU_PLATFORM_RESOURCE_H
#define __NPU_PLATFORM_RESOURCE_H
#include "global_ddr_map.h"

#define DEVDRV_PLAT_STREAM_MAX     128
#define DEVDRV_PLAT_EVENT_MAX      256
#define DEVDRV_PLAT_NOTIFY_MAX     1024
#define DEVDRV_PLAT_MODEL_MAX      64
#define DEVDRV_PLAT_AICORE_MAX     1
#define DEVDRV_PLAT_AICPU_MAX      1
#define DEVDRV_PLAT_CALC_SQ_MAX    64
#define DEVDRV_PLAT_CALC_SQ_DEPTH  256
#define DEVDRV_PLAT_CALC_CQ_MAX    1
#define DEVDRV_PLAT_CALC_CQ_DEPTH  1024
#define DEVDRV_PLAT_DFX_SQ_MAX     4
#define DEVDRV_PLAT_DFX_CQ_MAX     10
#define DEVDRV_PLAT_DFX_SQCQ_DEPTH 1024
#define DEVDRV_PLAT_DOORBELL_STRIDE 4096  /* stride 4KB */

#define TMP_LOG_BUF_SIZE    0x80000
#define TMP_LOG_BUFER_BASE  0x302E0000


#define NPU_NONSEC_RESERVED_DDR_BASE_ADDR  (HISI_RESERVED_NPU_AI_SERVER_PHYMEM_BASE)
#define NPU_SEC_RESERVED_DDR_BASE_ADDR  (HISI_RESERVED_NPU_SEC_PHYMEM_BASE)

#define NPU_NONSEC_RESERVED_AICPU_FW_SIZE       0x300000
#define NPU_NONSEC_RESERVED_TSCPU_FW_SIZE       0x400000
#define NPU_NONSEC_RESERVED_SQCQ_SIZE           0x180000
#define NPU_NONSEC_RESERVED_TASK_POOL_SIZE      0x100000
#define NPU_NONSEC_RESERVED_LOG_SIZE            0x80000
#define NPU_NONSEC_RESERVED_PROF_SIZE           0x100000
#define NPU_NONSEC_RESERVED_BBOX_SIZE           0x40000
#define NPU_NONSEC_RESERVED_DATADUMP_SIZE       0xc0000


#define NPU_NONSEC_RESERVED_AICPU_FW_BASE_ADDR	NPU_NONSEC_RESERVED_DDR_BASE_ADDR

#define NPU_NONSEC_RESERVED_TSCPU_FW_BASE_ADDR	(NPU_NONSEC_RESERVED_AICPU_FW_BASE_ADDR \
												+ NPU_NONSEC_RESERVED_AICPU_FW_SIZE)

#define NPU_NONSEC_RESERVED_SQCQ_BASE_ADDR		(NPU_NONSEC_RESERVED_TSCPU_FW_BASE_ADDR \
												+ NPU_NONSEC_RESERVED_TSCPU_FW_SIZE)

#define NPU_NONSEC_RESERVED_TASK_POOL_BASE_ADDR (NPU_NONSEC_RESERVED_SQCQ_BASE_ADDR \
												+ NPU_NONSEC_RESERVED_SQCQ_SIZE)

#define NPU_NONSEC_RESERVED_LOG_BASE_ADDR		(NPU_NONSEC_RESERVED_TASK_POOL_BASE_ADDR \
												+ NPU_NONSEC_RESERVED_TASK_POOL_SIZE)

#define NPU_NONSEC_RESERVED_PROF_BASE_ADDR		(NPU_NONSEC_RESERVED_LOG_BASE_ADDR \
												+ NPU_NONSEC_RESERVED_LOG_SIZE)

#define NPU_NONSEC_RESERVED_BBOX_BASE_ADDR		(NPU_NONSEC_RESERVED_PROF_BASE_ADDR \
												+ NPU_NONSEC_RESERVED_PROF_SIZE)

#define NPU_NONSEC_RESERVED_DATADUMP_BASE_ADDR	(NPU_NONSEC_RESERVED_BBOX_BASE_ADDR \
												+ NPU_NONSEC_RESERVED_BBOX_SIZE)


enum devdrv_dump_region_index {
	DEVDRV_DUMP_REGION_NPU_CRG,
	DEVDRV_DUMP_REGION_MAX
};
#endif
